const TOGGLE_ALL_TRANSFER_VARIANTS = 'TOGGLE_ALL_TRANSFER_VARIANTS'
const TOGGLE_WITHOUT_TRANSFER = 'TOGGLE_WITHOUT_TRANSFER'
const TOGGLE_ONE_TRANSFER = 'TOGGLE_ONE_TRANSFER'
const TOGGLE_TWO_TRANSFERS = 'TOGGLE_TWO_TRANSFERS'
const TOGGLE_THREE_TRANSFERS = 'TOGGLE_THREE_TRANSFERS'

export default {
  TOGGLE_ALL_TRANSFER_VARIANTS,
  TOGGLE_WITHOUT_TRANSFER,
  TOGGLE_ONE_TRANSFER,
  TOGGLE_TWO_TRANSFERS,
  TOGGLE_THREE_TRANSFERS,
}
