const GET_CHEAPEST = 'GET_CHEAPEST'
const GET_FASTEST = 'GET_FASTEST'
const GET_OPTIMAL = 'GET_OPTIMAL'
const ADD_TICKETS = 'ADD_TICKETS'

export default {
  GET_CHEAPEST,
  GET_FASTEST,
  GET_OPTIMAL,
  ADD_TICKETS,
}
